# Generated by Django 4.1.4 on 2022-12-29 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('logo', models.URLField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(default=0.0)),
                ('PaymentDate', models.DateField(auto_now_add=True)),
                ('ExpirationDate', models.DateField(null=True)),
                ('Service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_id', to='versionedPagos.services')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penalty_fee_amount', models.FloatField(default=0.0)),
                ('Payment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_expired', to='versionedPagos.payment')),
            ],
        ),
    ]
